#########################################################################
# Title:         Pre-Tasks: Git Task                                    #
# Author(s):     salty                                                  #
# URL:           https://github.com/shaboigan/Reddbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Git | Lookup git safe directories
  ansible.builtin.shell: git config --global -l
  register: git_config
  ignore_errors: true
  when: (not 'preinstall' in ansible_run_tags)

- name: Git | Set Reddbox repository as safe directory
  ansible.builtin.shell: git config --global --add safe.directory /srv/git/reddbox
  when: ('preinstall' in ansible_run_tags) or (not '/srv/git/reddbox' in git_config.stdout)

- name: Git | Set sb repository as safe directory
  ansible.builtin.shell: git config --global --add safe.directory /srv/git/sb
  when: ('preinstall' in ansible_run_tags) or (not '/srv/git/sb' in git_config.stdout)

- name: Git | Set Reddbox repository as safe directory
  ansible.builtin.shell: git config --global --add safe.directory /opt/sandbox
  when: ('preinstall' in ansible_run_tags) or (not '/opt/sandbox' in git_config.stdout)
