#########################################################################
# Title:         Pre-Tasks: Variables Tasks                             #
# Author(s):     salty                                                  #
# URL:           https://github.com/shaboigan/Reddbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Find Reddbox roles
  ansible.builtin.shell: "find /srv/git/reddbox/roles -type d -name 'defaults'"
  register: reddbox_roles

- name: Include Reddbox role default vars
  ansible.builtin.include_vars: "{{ item }}/main.yml"
  with_items: "{{ reddbox_roles.stdout_lines }}"

- name: Reddbox
  when: (playbook_dir == "/opt/reddbox_mod")
  block:
    - name: Find Reddbox roles
      ansible.builtin.shell: "find /opt/sandbox/roles -type d -name 'defaults'"
      register: sandbox_roles

    - name: Include Reddbox role default vars
      ansible.builtin.include_vars: "{{ item }}/main.yml"
      with_items: "{{ sandbox_roles.stdout_lines }}"

- name: Check if 'localhost.yml' exists
  ansible.builtin.stat:
    path: "/srv/git/reddbox/inventories/host_vars/localhost.yml"
  register: localhost_inventory_file

- name: Import Inventory variables
  ansible.builtin.include_vars: "/srv/git/reddbox/inventories/host_vars/localhost.yml"
  when: localhost_inventory_file.stat.exists
