#########################################################################
# Title:         Reddbox: Sanity Check | System                         #
# Author(s):     l3uddz, desimaniac, salty                              #
# URL:           https://github.com/shaboigan/Reddbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: System | Ensure Ansible is running on Raspbian 10
  ansible.builtin.assert:
    that:
      - ((ansible_distribution == 'Raspbian') and (ansible_facts['distribution_version'] is version('10', '>=')))
    fail_msg: >-
      Reddbox was designed for use on Raspbian servers running version 10.
    success_msg: >-
      System is running {{ ansible_lsb.description if ansible_lsb is defined else (ansible_distribution + ' ' + ansible_distribution_version) }}.
