#########################################################################
# Title:         Reddbox: Sanity Check | Logs                           #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/shaboigan/Reddbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Logs | Get '{{ sanity_check_logs_playbook_path | basename }}' info
  ansible.builtin.stat:
    path: "{{ sanity_check_logs_playbook_path }}"
  register: reddbox_yml

- name: Logs | Touch '{{ sanity_check_logs_logfile_path | basename }}'
  ansible.builtin.file:
    path: "{{ sanity_check_logs_logfile_path }}"
    state: touch
    owner: "{{ reddbox_yml.stat.uid }}"
    group: "{{ reddbox_yml.stat.gid }}"
    mode: 0664
