#########################################################################
# Title:         Reddbox: Sanity Check | Skipped Tags                   #
# Author(s):     salty                                                  #
# URL:           https://github.com/shaboigan/Reddbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Skipped Tags | Print Skipped Tags
  ansible.builtin.debug:
    msg: "{{ ansible_skip_tags }}"
