##########################################################################
# Title:         Reddbox: Custom | Default Variables                     #
# Author(s):     salty                                                   #
# URL:           https://github.com/shaboigan/Reddbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
custom_apt: []

custom_pip: []
