##########################################################################
# Title:         Reddbox: Cloudflared | Default Variables                   #
# Author(s):     salty                                                   #
# URL:           https://github.com/shaboigan/Reddbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

cloudflared_instances: ["cloudflared"]

################################
# Docker
################################

# Container
cloudflared_docker_container: "{{ cloudflared_name }}"

# Image
cloudflared_docker_image_pull: true
cloudflared_docker_image_repo: "cloudflare/cloudflared"
cloudflared_docker_image_tag: "latest"
cloudflared_docker_image: "{{ lookup('vars', cloudflared_name + '_docker_image_repo', default=cloudflared_docker_image_repo)
                           + ':' + lookup('vars', cloudflared_name + '_docker_image_tag', default=cloudflared_docker_image_tag) }}"

# Envs
cloudflared_docker_envs_default:
  TZ: "{{ tz }}"
  TUNNEL_TOKEN: "{{ cloudflared.token }}"
cloudflared_docker_envs_custom: {}
cloudflared_docker_envs: "{{ lookup('vars', cloudflared_name + '_docker_envs_default', default=cloudflared_docker_envs_default)
                          | combine(lookup('vars', cloudflared_name + '_docker_envs_custom', default=cloudflared_docker_envs_custom)) }}"

# Commands
cloudflared_docker_commands_default: 
  "tunnel --no-autoupdate run --token {{ cloudflared.token }}"
cloudflared_docker_commands_custom: []
cloudflared_docker_commands: "{{ lookup('vars', cloudflared_name + '_docker_commands_default', default=cloudflared_docker_commands_default)
                              + lookup('vars', cloudflared_name + '_docker_docker_commands_custom', default=cloudflared_docker_commands_custom) }}"

# Devices
cloudflared_docker_devices_default: []
cloudflared_docker_devices_custom: []
cloudflared_docker_devices: "{{ lookup('vars', cloudflared_name + '_docker_devices_default', default=cloudflared_docker_devices_default)
                             + lookup('vars', cloudflared_name + '_docker_devices_custom', default=cloudflared_docker_devices_custom) }}"

# Hosts
cloudflared_docker_hosts_default: []
cloudflared_docker_hosts_custom: []
cloudflared_docker_hosts: "{{ docker_hosts_common
                           | combine(lookup('vars', cloudflared_name + '_docker_hosts_default', default=cloudflared_docker_hosts_default))
                           | combine(lookup('vars', cloudflared_name + '_docker_hosts_custom', default=cloudflared_docker_hosts_custom)) }}"

# Labels
cloudflared_docker_labels_default: {}
cloudflared_docker_labels_custom: {}
cloudflared_docker_labels: "{{ docker_labels_common
                            | combine(lookup('vars', cloudflared_name + '_docker_labels_default', default=cloudflared_docker_labels_default))
                            | combine(lookup('vars', cloudflared_name + '_docker_labels_custom', default=cloudflared_docker_labels_custom)) }}"

# Hostname
cloudflared_docker_hostname: "{{ cloudflared_name }}"

# Networks
cloudflared_docker_networks_alias: "{{ cloudflared_name }}"
cloudflared_docker_networks_default: []
cloudflared_docker_networks_custom: []
cloudflared_docker_networks: "{{ docker_networks_common
                              + lookup('vars', cloudflared_name + '_docker_networks_default', default=cloudflared_docker_networks_default)
                              + lookup('vars', cloudflared_name + '_docker_networks_custom', default=cloudflared_docker_networks_custom) }}"

# Capabilities
cloudflared_docker_capabilities_default: []
cloudflared_docker_capabilities_custom: []
cloudflared_docker_capabilities: "{{ lookup('vars', cloudflared_name + '_docker_capabilities_default', default=cloudflared_docker_capabilities_default)
                                  + lookup('vars', cloudflared_name + '_docker_capabilities_custom', default=cloudflared_docker_capabilities_custom) }}"

# Security Opts
cloudflared_docker_security_opts_default: []
cloudflared_docker_security_opts_custom: []
cloudflared_docker_security_opts: "{{ lookup('vars', cloudflared_name + '_docker_security_opts_default', default=cloudflared_docker_security_opts_default)
                                   + lookup('vars', cloudflared_name + '_docker_security_opts_custom', default=cloudflared_docker_security_opts_custom) }}"

# Restart Policy
cloudflared_docker_restart_policy: unless-stopped

# State
cloudflared_docker_state: started

# User
cloudflared_docker_user: "{{ uid }}:{{ gid }}"
