##########################################################################
# Title:         Reddbox: Media Server | Default Variables               #
# Author(s):     salty                                                   #
# URL:           https://github.com/shaboigan/Reddbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
media_servers_enabled: ["plex"]
