##########################################################################
# Title:         Reddbox: TasmoAdmin | Default Variables                 #
# Author(s):     shaboigan                                               #
# URL:           https://github.com/shaboigan/Reddbox                    #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

tasmoadmin_instances: ["tasmoadmin"]

################################
# Paths
################################

tasmoadmin_paths_folder: "{{ tasmoadmin_name }}"
tasmoadmin_paths_location: "{{ server_appdata_path }}/{{ tasmoadmin_paths_folder }}"
tasmoadmin_paths_folders_list:
  - "{{ tasmoadmin_paths_location }}"

################################
# Web
################################

tasmoadmin_web_subdomain: "{{ tasmoadmin_name }}"
tasmoadmin_web_domain: "{{ user.domain }}"
tasmoadmin_web_port: "5555"
tasmoadmin_web_url: "{{ 'https://' + lookup('vars', tasmoadmin_name + '_web_subdomain', default=tasmoadmin_web_subdomain)
                      + '.' + lookup('vars', tasmoadmin_name + '_web_domain', default=tasmoadmin_web_domain) }}"

################################
# DNS
################################

tasmoadmin_dns_record: "{{ lookup('vars', tasmoadmin_name + '_web_subdomain', default=tasmoadmin_web_subdomain) }}"
tasmoadmin_dns_zone: "{{ lookup('vars', tasmoadmin_name + '_web_domain', default=tasmoadmin_web_domain) }}"
tasmoadmin_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

tasmoadmin_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"

tasmoadmin_traefik_middleware_default: "{{ traefik_default_middleware + ','
                                       + lookup('vars', tasmoadmin_name + '_traefik_sso_middleware', default=tasmoadmin_traefik_sso_middleware)
                                    if (lookup('vars', tasmoadmin_name + '_traefik_sso_middleware', default=tasmoadmin_traefik_sso_middleware) | length > 0)
                                    else traefik_default_middleware }}"
tasmoadmin_traefik_middleware_custom: ""
tasmoadmin_traefik_middleware: "{{ tasmoadmin_traefik_middleware_default + ','
                               + tasmoadmin_traefik_middleware_custom
                            if (not tasmoadmin_traefik_middleware_custom.startswith(',') and tasmoadmin_traefik_middleware_custom | length > 0)
                            else tasmoadmin_traefik_middleware_default
                               + tasmoadmin_traefik_middleware_custom }}"

tasmoadmin_traefik_certresolver: "{{ traefik_default_certresolver }}"
tasmoadmin_traefik_enabled: false
tasmoadmin_traefik_api_enabled: false
tasmoadmin_traefik_api_endpoint: "`/auth`,`/settings`,`/flows`,`/flow`,`/nodes`"

################################
# Docker
################################

# Container
tasmoadmin_docker_container: "{{ tasmoadmin_name }}"

# Image
tasmoadmin_docker_image_pull: true
tasmoadmin_docker_image_repo: "ghcr.io/tasmoadmin/tasmoadmin"
tasmoadmin_docker_image_tag: "latest"
tasmoadmin_docker_image: "{{ lookup('vars', tasmoadmin_name + '_docker_image_repo', default=tasmoadmin_docker_image_repo)
                           + ':' + lookup('vars', tasmoadmin_name + '_docker_image_tag', default=tasmoadmin_docker_image_tag) }}"

# Ports
tasmoadmin_docker_ports_defaults: []
tasmoadmin_docker_ports_custom: []
tasmoadmin_docker_ports: "{{ lookup('vars', tasmoadmin_name + '_docker_ports_defaults', default=tasmoadmin_docker_ports_defaults)
                           + lookup('vars', tasmoadmin_name + '_docker_ports_custom', default=tasmoadmin_docker_ports_custom) }}"

# Envs
tasmoadmin_docker_envs_default:
  TZ: "{{ tz }}"
tasmoadmin_docker_envs_custom: {}
tasmoadmin_docker_envs: "{{ lookup('vars', tasmoadmin_name + '_docker_envs_default', default=tasmoadmin_docker_envs_default)
                          | combine(lookup('vars', tasmoadmin_name + '_docker_envs_custom', default=tasmoadmin_docker_envs_custom)) }}"

# Commands
tasmoadmin_docker_commands_default: []
tasmoadmin_docker_commands_custom: []
tasmoadmin_docker_commands: "{{ lookup('vars', tasmoadmin_name + '_docker_commands_default', default=tasmoadmin_docker_commands_default)
                              + lookup('vars', tasmoadmin_name + '_docker_docker_commands_custom', default=tasmoadmin_docker_commands_custom) }}"

# Volumes
tasmoadmin_docker_volumes_default:
  - "{{ tasmoadmin_paths_location }}:/data"
tasmoadmin_docker_volumes_custom: []
tasmoadmin_docker_volumes: "{{ lookup('vars', tasmoadmin_name + '_docker_volumes_default', default=tasmoadmin_docker_volumes_default)
                             + lookup('vars', tasmoadmin_name + '_docker_volumes_custom', default=tasmoadmin_docker_volumes_custom) }}"

# Devices
tasmoadmin_docker_devices_default: []
tasmoadmin_docker_devices_custom: []
tasmoadmin_docker_devices: "{{ lookup('vars', tasmoadmin_name + '_docker_devices_default', default=tasmoadmin_docker_devices_default)
                             + lookup('vars', tasmoadmin_name + '_docker_devices_custom', default=tasmoadmin_docker_devices_custom) }}"

# Hosts
tasmoadmin_docker_hosts_default: []
tasmoadmin_docker_hosts_custom: []
tasmoadmin_docker_hosts: "{{ docker_hosts_common
                           | combine(lookup('vars', tasmoadmin_name + '_docker_hosts_default', default=tasmoadmin_docker_hosts_default))
                           | combine(lookup('vars', tasmoadmin_name + '_docker_hosts_custom', default=tasmoadmin_docker_hosts_custom)) }}"

# Labels
tasmoadmin_docker_labels_default: {}
tasmoadmin_docker_labels_custom: {}
tasmoadmin_docker_labels: "{{ docker_labels_common
                            | combine(lookup('vars', tasmoadmin_name + '_docker_labels_default', default=tasmoadmin_docker_labels_default))
                            | combine(lookup('vars', tasmoadmin_name + '_docker_labels_custom', default=tasmoadmin_docker_labels_custom)) }}"

# Hostname
tasmoadmin_docker_hostname: "{{ tasmoadmin_name }}"

# Networks
tasmoadmin_docker_networks_alias: "{{ tasmoadmin_name }}"
tasmoadmin_docker_networks_default: []
tasmoadmin_docker_networks_custom: []
tasmoadmin_docker_networks: "{{ docker_networks_common
                              + lookup('vars', tasmoadmin_name + '_docker_networks_default', default=tasmoadmin_docker_networks_default)
                              + lookup('vars', tasmoadmin_name + '_docker_networks_custom', default=tasmoadmin_docker_networks_custom) }}"

# Capabilities
tasmoadmin_docker_capabilities_default: []
tasmoadmin_docker_capabilities_custom: []
tasmoadmin_docker_capabilities: "{{ lookup('vars', tasmoadmin_name + '_docker_capabilities_default', default=tasmoadmin_docker_capabilities_default)
                                  + lookup('vars', tasmoadmin_name + '_docker_capabilities_custom', default=tasmoadmin_docker_capabilities_custom) }}"

# Security Opts
tasmoadmin_docker_security_opts_default: []
tasmoadmin_docker_security_opts_custom: []
tasmoadmin_docker_security_opts: "{{ lookup('vars', tasmoadmin_name + '_docker_security_opts_default', default=tasmoadmin_docker_security_opts_default)
                                   + lookup('vars', tasmoadmin_name + '_docker_security_opts_custom', default=tasmoadmin_docker_security_opts_custom) }}"

# Restart Policy
tasmoadmin_docker_restart_policy: unless-stopped

# State
tasmoadmin_docker_state: started

# User
tasmoadmin_docker_user: "{{ uid }}:{{ gid }}"
