#########################################################################
# Title:         Reddbox: Nginx Proxy Manager Role                                 #
# Author(s):     salty                                                  #
# URL:           https://github.com/shaboigan/Reddbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Execute Nginx Proxy Manager roles"
  ansible.builtin.include_tasks: main2.yml
  vars:
    nginx_proxy_manager_name: "{{ role }}"
  with_items: "{{ nginx_proxy_manager_instances }}"
  loop_control:
    loop_var: role
