##########################################################################
# Title:         Reddbox: WIP | Default Variables                     #
# Author(s):     salty                                                   #
# URL:           https://github.com/shaboigan/Reddbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

pihole_instances: ["pihole"]

################################
# Paths
################################

pihole_paths_folder: "{{ pihole_name }}"
pihole_paths_location: "{{ server_appdata_path }}/{{ pihole_paths_folder }}"
pihole_paths_folders_list:
  - "{{ pihole_paths_location }}"

################################
# Web
################################

pihole_web_subdomain: "{{ pihole_name }}"
pihole_web_domain: "{{ user.domain }}"
pihole_web_port: "1880"
pihole_web_url: "{{ 'https://' + lookup('vars', pihole_name + '_web_subdomain', default=pihole_web_subdomain)
                      + '.' + lookup('vars', pihole_name + '_web_domain', default=pihole_web_domain) }}"

################################
# DNS
################################

pihole_dns_record: "{{ lookup('vars', pihole_name + '_web_subdomain', default=pihole_web_subdomain) }}"
pihole_dns_zone: "{{ lookup('vars', pihole_name + '_web_domain', default=pihole_web_domain) }}"
pihole_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

pihole_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"

pihole_traefik_middleware_default: "{{ traefik_default_middleware + ','
                                       + lookup('vars', pihole_name + '_traefik_sso_middleware', default=pihole_traefik_sso_middleware)
                                    if (lookup('vars', pihole_name + '_traefik_sso_middleware', default=pihole_traefik_sso_middleware) | length > 0)
                                    else traefik_default_middleware }}"
pihole_traefik_middleware_custom: ""
pihole_traefik_middleware: "{{ pihole_traefik_middleware_default + ','
                               + pihole_traefik_middleware_custom
                            if (not pihole_traefik_middleware_custom.startswith(',') and pihole_traefik_middleware_custom | length > 0)
                            else pihole_traefik_middleware_default
                               + pihole_traefik_middleware_custom }}"

pihole_traefik_certresolver: "{{ traefik_default_certresolver }}"
pihole_traefik_enabled: false
pihole_traefik_api_enabled: false
pihole_traefik_api_endpoint: "`/auth`,`/settings`,`/flows`,`/flow`,`/nodes`"

################################
# Docker
################################

# Container
pihole_docker_container: "{{ pihole_name }}"

# Image
pihole_docker_image_pull: true
pihole_docker_image_repo: "pihole/pihole"
pihole_docker_image_tag: "latest"
pihole_docker_image: "{{ lookup('vars', pihole_name + '_docker_image_repo', default=pihole_docker_image_repo)
                           + ':' + lookup('vars', pihole_name + '_docker_image_tag', default=pihole_docker_image_tag) }}"

# Ports
pihole_docker_ports_defaults:
  - "53:53/tcp"
  - "53:53/udp"
  - "80:80/tcp"
pihole_docker_ports_custom: []
pihole_docker_ports: "{{ lookup('vars', pihole_name + '_docker_ports_defaults', default=pihole_docker_ports_defaults)
                           + lookup('vars', pihole_name + '_docker_ports_custom', default=pihole_docker_ports_custom) }}"

# Envs
pihole_docker_envs_default:
  TZ: "{{ tz }}"
pihole_docker_envs_custom: {}
pihole_docker_envs: "{{ lookup('vars', pihole_name + '_docker_envs_default', default=pihole_docker_envs_default)
                          | combine(lookup('vars', pihole_name + '_docker_envs_custom', default=pihole_docker_envs_custom)) }}"

# Commands
pihole_docker_commands_default: []
pihole_docker_commands_custom: []
pihole_docker_commands: "{{ lookup('vars', pihole_name + '_docker_commands_default', default=pihole_docker_commands_default)
                              + lookup('vars', pihole_name + '_docker_docker_commands_custom', default=pihole_docker_commands_custom) }}"

# Volumes
pihole_docker_volumes_default:
  - "{{ pihole_paths_location }}:/data"
pihole_docker_volumes_custom: []
pihole_docker_volumes: "{{ lookup('vars', pihole_name + '_docker_volumes_default', default=pihole_docker_volumes_default)
                             + lookup('vars', pihole_name + '_docker_volumes_custom', default=pihole_docker_volumes_custom) }}"

# Devices
pihole_docker_devices_default: []
pihole_docker_devices_custom: []
pihole_docker_devices: "{{ lookup('vars', pihole_name + '_docker_devices_default', default=pihole_docker_devices_default)
                             + lookup('vars', pihole_name + '_docker_devices_custom', default=pihole_docker_devices_custom) }}"

# Hosts
pihole_docker_hosts_default: []
pihole_docker_hosts_custom: []
pihole_docker_hosts: "{{ docker_hosts_common
                           | combine(lookup('vars', pihole_name + '_docker_hosts_default', default=pihole_docker_hosts_default))
                           | combine(lookup('vars', pihole_name + '_docker_hosts_custom', default=pihole_docker_hosts_custom)) }}"

# Labels
pihole_docker_labels_default: {}
pihole_docker_labels_custom: {}
pihole_docker_labels: "{{ docker_labels_common
                            | combine(lookup('vars', pihole_name + '_docker_labels_default', default=pihole_docker_labels_default))
                            | combine(lookup('vars', pihole_name + '_docker_labels_custom', default=pihole_docker_labels_custom)) }}"

# Hostname
pihole_docker_hostname: "{{ pihole_name }}"

# Networks
pihole_docker_networks_alias: "{{ pihole_name }}"
pihole_docker_networks_default: []
pihole_docker_networks_custom: []
pihole_docker_networks: "{{ docker_networks_common
                              + lookup('vars', pihole_name + '_docker_networks_default', default=pihole_docker_networks_default)
                              + lookup('vars', pihole_name + '_docker_networks_custom', default=pihole_docker_networks_custom) }}"

# Capabilities
pihole_docker_capabilities_default: []
pihole_docker_capabilities_custom: []
pihole_docker_capabilities: "{{ lookup('vars', pihole_name + '_docker_capabilities_default', default=pihole_docker_capabilities_default)
                                  + lookup('vars', pihole_name + '_docker_capabilities_custom', default=pihole_docker_capabilities_custom) }}"

# Security Opts
pihole_docker_security_opts_default: []
pihole_docker_security_opts_custom: []
pihole_docker_security_opts: "{{ lookup('vars', pihole_name + '_docker_security_opts_default', default=pihole_docker_security_opts_default)
                                   + lookup('vars', pihole_name + '_docker_security_opts_custom', default=pihole_docker_security_opts_custom) }}"

# Restart Policy
pihole_docker_restart_policy: unless-stopped

# State
pihole_docker_state: started

# User
pihole_docker_user: "{{ uid }}:{{ gid }}"
