#########################################################################
# Title:         Reddbox: Cloudflare | Subdomains Task                  #
# Author(s):     desimaniac, salty                                      #
# URL:           https://github.com/shaboigan/Reddbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
## Add 'reddbox_type' subdomain
- name: "Cloudflare | Subdomains | Add '{{ reddbox_type }}' subdomain to '{{ fld.stdout }}'"
  ansible.builtin.import_tasks: "subdomains/add_subdomain.yml"

## Remove 'reddbox' subdomain for Mediabox/Feederbox setups.
- name: "Cloudflare | Subdomains | Remove 'reddbox' subdomain from '{{ fld.stdout }}'"
  ansible.builtin.import_tasks: "subdomains/remove_subdomain.yml"
  when: reddbox_type is regex('mediabox|feederbox')
