#########################################################################
# Title:         Reddbox: Cloudflared Role                                 #
# Author(s):     salty                                                  #
# URL:           https://github.com/shaboigan/Reddbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Execute Cloudfalred roles"
  ansible.builtin.include_tasks: main2.yml
  vars:
    cloudflared_name: "{{ role }}"
  with_items: "{{ cloudflared_instances }}"
  loop_control:
    loop_var: role
